Problem 1: Decision Trees

In [48]:
import pandas as pd
from ucimlrepo import fetch_ucirepo
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, log_loss

In [42]:
# import fetch dataset 
spambase = fetch_ucirepo(id=94) 
  
# data (as pandas dataframes) 
X = spambase.data.features 
y = spambase.data.targets 
  
# metadata 
#print(spambase.metadata) 
  
# variable information 
#print(spambase.variables)

1. Use an existing package to train a decision tree on the SPAMBASE training data, without pruning. Use the information gain splitting criteria. Compute the training and the testing error, accuracy, F1 score, and AUC and report these metrics. Write down some observations about the training and testing metrics.

In [43]:
# split data into training and test sets:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True)

tree = tree.DecisionTreeClassifier(criterion='entropy')
tree.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [44]:
# outputs:
rows = []

for train_or_test, x, y_true in [("Train", X_train, y_train),
                                  ("Test",  X_test,  y_test)]:
    
    y_pred = tree.predict(x)

    rows.append({
        "Train or Test": train_or_test,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Error": log_loss(y_true, y_pred),
        "F1": f1_score(y_true, y_pred),
        "AUC": roc_auc_score(y_true, y_pred)
    })


pd.DataFrame(rows).set_index("Train or Test")

               Accuracy     Error        F1       AUC
Train or Test
Train          0.999457  0.019589  0.999297  0.999297
Test           0.927253  2.622068  0.912418  0.922954

observations about training and testing metrics:

In [45]:
print("Training set:")
print("Accuracy score: ", accuracy_score(y_train, y_pred_train))
print("Error : ", log_loss(y_train, y_pred_train))
print("F1 score: ", f1_score(y_train, y_pred_train))
print("AUC: ", roc_auc_score(y_train, y_pred_train))

print("Test set:")
print("Accuracy score: ", accuracy_score(y_test, y_pred_test))
print("Error : ", log_loss(y_test, y_pred_test))
print("F1 score: ", f1_score(y_test, y_pred_test))
print("AUC: ", roc_auc_score(y_test, y_pred_test))

Training set:
Accuracy score:  0.9994565217391305
Error :  0.019588942059303022
F1 score:  0.99929676511955
AUC:  0.9992972593113141
Test set:
Accuracy score:  0.9305103148751357
Error :  2.504662124759498
F1 score:  0.9162303664921465
AUC:  0.9261190786614515

2. Change the splitting criteria to use the Gini index. and report the same metrics. Compare them to the information gain metrics.

In [52]:
tree_gini = tree.DecisionTreeClassifier(criterion='entropy')
tree_gini.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [53]:
# outputs:
rows = []

for train_or_test, x, y_true in [("Train", X_train, y_train),
                                  ("Test",  X_test,  y_test)]:
    
    y_pred = tree_gini.predict(x)

    rows.append({
        "Train or Test": train_or_test,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Error": log_loss(y_true, y_pred),
        "F1": f1_score(y_true, y_pred),
        "AUC": roc_auc_score(y_true, y_pred)
    })


pd.DataFrame(rows).set_index("Train or Test")

               Accuracy     Error        F1       AUC
Train or Test
Train          0.999457  0.019589  0.999297  0.999297
Test           0.930510  2.504662  0.916667  0.926800