In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
# import train dataset
train = pd.read_csv('train.csv')
train.head()

,Unnamed: 0,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,1,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,2,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,3,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,4,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,5,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [3]:
# import test dataset
test = pd.read_csv('test.csv')
test.head()

,Unnamed: 0,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,1001,3131200640,20150427T000000,700000.0,4,2.00,1830,4590,2.0,0,...,8,1830,0,1908,0,98105,47.6593,-122.327,1650,4590
1,1002,984000710,20141022T000000,270000.0,3,2.00,1560,8853,1.0,0,...,7,1560,0,1967,0,98058,47.4312,-122.171,1610,8750
2,1003,4167300350,20140508T000000,258000.0,4,1.75,1730,8320,1.0,0,...,7,1230,500,1977,0,98023,47.3270,-122.361,1840,9800
3,1004,2826049282,20140614T000000,530000.0,3,2.50,1930,7214,2.0,0,...,8,1930,0,2005,0,98125,47.7191,-122.309,1930,7266
4,1005,8946750030,20141218T000000,245000.0,3,2.25,1422,3677,2.0,0,...,7,1422,0,2012,0,98092,47.3204,-122.178,1677,3677

In [4]:
# TRAIN:
# ignore columns: id, date and zipcode
# also ignore price column because this is the response and what we are trying to predict
columns_to_drop = ['Unnamed: 0', 'zipcode', 'price']
x_train = train.drop(columns=columns_to_drop)
x_train.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15
0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,47.5112,-122.257,1340,5650
1,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,47.7210,-122.319,1690,7639
2,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,47.7379,-122.233,2720,8062
3,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,47.5208,-122.393,1360,5000
4,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,47.6168,-122.045,1800,7503

In [5]:
# TEST:
# ignore columns: id, date and zipcode
# also ignore price column because this is the response and what we are trying to predict
columns_to_drop = ['Unnamed: 0', 'id', 'date', 'zipcode', 'price']
x_test = test.drop(columns=columns_to_drop)
x_test.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15
0,4,2.00,1830,4590,2.0,0,0,3,8,1830,0,1908,0,47.6593,-122.327,1650,4590
1,3,2.00,1560,8853,1.0,0,0,3,7,1560,0,1967,0,47.4312,-122.171,1610,8750
2,4,1.75,1730,8320,1.0,0,0,3,7,1230,500,1977,0,47.3270,-122.361,1840,9800
3,3,2.50,1930,7214,2.0,0,0,3,8,1930,0,2005,0,47.7191,-122.309,1930,7266
4,3,2.25,1422,3677,2.0,0,0,3,7,1422,0,2012,0,47.3204,-122.178,1677,3677

In [6]:
# scale the data so that each feature has a mean of 0 and standard deviation of 1
scaler = StandardScaler()

# scale train dataset
for col in x_train:
    train_scaled = x_train[col].values.reshape(-1, 1) #reshape
    x_train[col] = scaler.fit_transform(train_scaled) 

# scale test dataset
for col in x_test:
    test_scaled = x_test[col].values.reshape(-1, 1) #reshape
    x_test[col] = scaler.fit_transform(test_scaled) 


# check mean and standard deviation of each feature to double check that scaling worked
for feature in x_train:
    mean = x_train.mean()
    std = x_train.var()

for feature in x_test:
    mean = x_test.mean()
    std = x_test.var()

# organize all variables into a table
stats_train = {
    'mean': mean,
    'std': std
}

stats_test = {
   'mean': mean,
    'std': std
}

feature_data_train = pd.DataFrame(stats_train)
feature_data_test = pd.DataFrame(stats_test)
feature_data_test

                       mean       std
bedrooms      -1.385558e-16  1.001001
bathrooms      2.122746e-16  1.001001
sqft_living   -2.113865e-16  1.001001
sqft_lot      -1.421085e-17  1.001001
floors        -8.704149e-17  1.001001
waterfront    -2.842171e-17  1.001001
view          -8.792966e-17  1.001001
condition      1.776357e-16  1.001001
grade         -3.215206e-16  1.001001
sqft_above     2.842171e-17  1.001001
sqft_basement  3.241851e-17  1.001001
yr_built      -2.083667e-15  1.001001
yr_renovated  -1.065814e-17  1.001001
lat            2.316725e-14  1.001001
long          -2.620659e-14  1.001001
sqft_living15 -7.283063e-17  1.001001
sqft_lot15     3.197442e-17  1.001001

In [7]:
# divide the price by 1000 for all rows in the train dataset
y_train = train['price'] / 1000
y_test = test['price']/1000

In [8]:
# need to organize training data features into a matrix:
matrix_train = x_train.values
price_matrix_train = y_train.values

price_matrix_test = y_test.values

Consider a feature $X$, a response variable $Y$, and $N$ samples of training data. Implement a polynomial regression model that fits a polynomial of degree $p$ to the data using the least-square method. Use your own implementation from Problem 3 and adapt it for polynomial
regression. If $p=2$, the model will use two features ($X$ and $X^2$), if $p=3$ the model will use 3 features ($X,X^2,X^3$), and so on for larger values of $p$.

In [9]:
#X = feature, p = degree
def polynomial_regression(X, p):

    X = X.values # to matrix
    
    X = X.reshape(-1, 1)  # columns
    features = X.copy() # this is X to the first power
    
    for i in range(2, p+1): # start from exponent 2 bc we have X above
        
        features = np.append(features, X**i, axis=1)

    shape = features.shape[0]
    features = np.append(features, np.ones((shape,1)), axis=1)  

    return features

In [10]:
test = polynomial_regression(x_train['sqft_living'], 2)
#test

In [11]:
# implementation from problem 3 adapted for polynomial regression:
# theta = ((x^T)*x)^-1 * (x^T)y

def closed_form_calc_polynomial(matrix, price_matrix, p):

    matrix = polynomial_regression(matrix, p)

    xT_x = matrix.T @ matrix

    xTx_inv = np.linalg.pinv(xT_x) #pinv because singular

    xT_y = matrix.T @ price_matrix

    theta = xTx_inv @ xT_y

    return theta

In [12]:
x = x_test['sqft_living']
closed_form_calc_polynomial(x, price_matrix_test, 3)

x = x_train['sqft_living']
closed_form_calc_polynomial(x, price_matrix_train, 3)

array([211.35205591,  71.88636035, -12.32664809, 463.89399854])

In [13]:
def predict_response(x, theta):
    return x @ theta

Consider the house price prediction problem with feature $X=$ sqft_living. Train a polynomial regression model for different values of $p \le 5$ using your implementation. Include a table with the MSE and $R^2$ metrics on both the training and testing data for at least 3 different values of $p$. Discuss your observations on how the MSE and $R^2$ metrics change with the degree of the polynomial.

In [14]:
x = x_train['sqft_living']
ps = [0, 1, 2, 3, 4, 5]
mses = []
r_squared = []

for p in ps:
    
    poly = polynomial_regression(x, p)
    theta_poly = closed_form_calc_polynomial(x, price_matrix_train, p)

    y_pred = predict_response(poly, theta_poly)

    mses.append(mean_squared_error(price_matrix_train, y_pred))
    r_squared.append(r2_score(price_matrix_train, y_pred))


# organize all variables into a table
stats_train = {
    'p value': ps,
    'MSE metrics': mses,
    'R squared metrics': r_squared
}

print("Training data:")
data_train = pd.DataFrame(stats_train)
data_train

Training data:

   p value   MSE metrics  R squared metrics
0        0  57947.526161           0.496709
1        1  57947.526161           0.496709
2        2  54822.665116           0.523849
3        3  53785.194716           0.532860
4        4  52795.774758           0.541453
5        5  52626.111955           0.542927

In [15]:
x = x_test['sqft_living']
ps = [0, 1, 2, 3, 4, 5]
mses = []
r_squared = []

for p in ps:
    
    poly = polynomial_regression(x, p)
    theta_poly = closed_form_calc_polynomial(x, price_matrix_test, p)

    y_pred = predict_response(poly, theta_poly)

    mses.append(mean_squared_error(price_matrix_test, y_pred))
    r_squared.append(r2_score(price_matrix_test, y_pred))


# organize all variables into a table
stats_test = {
    'p value': ps,
    'MSE metrics': mses,
    'R squared metrics': r_squared
}

print("Test data:")
data_test = pd.DataFrame(stats_test)
data_test

Test data:

   p value   MSE metrics  R squared metrics
0        0  87697.728248           0.474004
1        1  87697.728248           0.474004
2        2  68945.240266           0.586478
3        3  64745.472068           0.611668
4        4  60817.708078           0.635226
5        5  59722.501992           0.641795

The MSE and R squared metrics change with the degree of the polynomial, or with different p values, where the MSE values decrease with each increasnig p value and the R squared metric increases with each increasing p value. This is observed in both training and test datasets.