In [13]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [3]:
# import house_data dataset
original_dataset = pd.read_csv('kc_house_data.csv')
original_dataset.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [5]:
# import training dataset
train = pd.read_csv('train.csv')
train.head()

,Unnamed: 0,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,1,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,2,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,3,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,4,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,5,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [12]:
# ignore columns: id, date and zipcode
# also ignore price column because this is the response and what we are trying to predict
features = train.drop(columns=['Unnamed: 0', 'zipcode', 'price'])
features.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15
0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,47.5112,-122.257,1340,5650
1,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,47.7210,-122.319,1690,7639
2,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,47.7379,-122.233,2720,8062
3,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,47.5208,-122.393,1360,5000
4,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,47.6168,-122.045,1800,7503

In [25]:
# scale the data so that each feature has a mean of 0 and standard deviation of 1
scaler = StandardScaler()

for col in features:
    new_col = features[col].values.reshape(-1, 1) #reshape
    features[col] = scaler.fit_transform(new_col) 


# check mean and standard deviation of each feature to double check that scaling worked
for feature in features:
    mean = features.mean()
    std = features.var()

# organize all variables into a table
stats = {
    'mean': mean,
    'std': std
}

feature_data = pd.DataFrame(stats)
feature_data

                       mean       std
bedrooms      -2.486900e-17  1.001001
bathrooms      1.065814e-17  1.001001
sqft_living    7.105427e-18  1.001001
sqft_lot      -5.329071e-18  1.001001
floors        -1.776357e-17  1.001001
waterfront    -1.065814e-17  1.001001
view           7.016610e-17  1.001001
condition      8.526513e-17  1.001001
grade         -2.131628e-17  1.001001
sqft_above    -1.065814e-17  1.001001
sqft_basement  7.105427e-18  1.001001
yr_built       7.105427e-18  1.001001
yr_renovated   0.000000e+00  1.001001
lat           -7.993606e-18  1.001001
long          -7.105427e-18  1.001001
sqft_living15  3.552714e-18  1.001001
sqft_lot15     1.776357e-18  1.001001
new            7.105427e-18  1.001001

In [24]:
# divide the price by 1000 for all rows in the dataset

train['price'] = train['price'] / 1000
train['price']

0      0.22190
1      0.53800
2      0.18000
3      0.60400
4      0.51000
        ...
995    0.29100
996    0.19995
997    0.55350
998    0.18995
999    0.28900
Name: price, Length: 1000, dtype: float64