In [8]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
# import train dataset
train = pd.read_csv('train.csv')
train.head()

,Unnamed: 0,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,1,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,2,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,3,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,4,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,5,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [3]:
# TRAIN:
# ignore columns: id, date and zipcode
# also ignore price column because this is the response and what we are trying to predict
columns_to_drop = ['Unnamed: 0', 'zipcode', 'price']
x_train = train.drop(columns=columns_to_drop)
x_train.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15
0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,47.5112,-122.257,1340,5650
1,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,47.7210,-122.319,1690,7639
2,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,47.7379,-122.233,2720,8062
3,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,47.5208,-122.393,1360,5000
4,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,47.6168,-122.045,1800,7503

In [6]:
# scale the data so that each feature has a mean of 0 and standard deviation of 1
scaler = StandardScaler()

# scale train dataset
for col in x_train:
    train_scaled = x_train[col].values.reshape(-1, 1) #reshape
    x_train[col] = scaler.fit_transform(train_scaled) 

# scale test dataset
#for col in x_test:
 #   test_scaled = x_test[col].values.reshape(-1, 1) #reshape
  #  x_test[col] = scaler.fit_transform(test_scaled) 


# check mean and standard deviation of each feature to double check that scaling worked
for feature in x_train:
    mean = x_train.mean()
    std = x_train.var()

#for feature in x_test:
 #   mean = x_test.mean()
  #  std = x_test.var()

# organize all variables into a table
stats_train = {
    'mean': mean,
    'std': std
}

#stats_test = {
 #   'mean': mean,
  #  'std': std
#}

feature_data_train = pd.DataFrame(stats_train)
#feature_data_test = pd.DataFrame(stats_test)
feature_data_train

                       mean       std
bedrooms      -1.936229e-16  1.001001
bathrooms      5.329071e-17  1.001001
sqft_living    8.881784e-17  1.001001
sqft_lot       3.730349e-17  1.001001
floors         2.433609e-16  1.001001
waterfront     1.065814e-17  1.001001
view           3.463896e-17  1.001001
condition      8.526513e-17  1.001001
grade          6.394885e-17  1.001001
sqft_above    -1.048051e-16  1.001001
sqft_basement  1.421085e-17  1.001001
yr_built       7.656098e-16  1.001001
yr_renovated   4.263256e-17  1.001001
lat           -1.293898e-14  1.001001
long          -3.200640e-14  1.001001
sqft_living15 -1.421085e-17  1.001001
sqft_lot15     1.776357e-18  1.001001

In [10]:
# divide the price by 1000 for all rows in the train dataset
y_train = train['price'] / 1000
y_train

0      221.90
1      538.00
2      180.00
3      604.00
4      510.00
        ...
995    291.00
996    199.95
997    553.50
998    189.95
999    289.00
Name: price, Length: 1000, dtype: float64

In [16]:
matrix_train = x_train.values
print(matrix_train)

price_matrix_train = y_train.values
print(price_matrix_train)

[[-0.40982347 -1.44988843 -0.98164572 ... -0.35519332 -0.96563661
  -0.3128578 ]
 [-0.40982347  0.28318404  0.58457767 ... -0.7998304  -0.44332966
  -0.23355563]
 [-1.58410276 -1.44988843 -1.44362529 ... -0.18307573  1.09374507
  -0.21669046]
 ...
 [-1.58410276 -1.44988843 -1.35348293 ... -0.86437449 -1.02532883
  -0.4185143 ]
 [-1.58410276 -1.44988843 -1.15066264 ...  1.07911986 -0.80148299
  -0.40352304]
 [-0.40982347 -0.06343045 -0.22670351 ... -0.46993837  0.39236146
  -0.15736334]]
[ 221.9    538.     180.     604.     510.    1225.     257.5    291.85
  229.5    323.     662.5    468.     310.     400.     530.     650.
  395.     485.     189.     230.     385.    2000.     285.     252.7
  329.     233.     937.     667.     438.     719.     580.5    280.
  687.5    535.     322.5    696.     550.     640.     240.     605.
  625.     775.     861.99   685.     309.     488.     210.49   785.
  450.    1350.     228.     345.     600.     585.     920.     885.
  292.5    301.     951.     430.     650.     289.     505.     549.
  425.     317.625  975.     287.     204.    1325.    1040.     325.
  571.     360.     349.     832.5    380.     480.     410.     720.
  390.     360.     355.     356.     315.     940.     305.     461.
  215.     335.     243.5   1099.88   153.     430.     700.     905.
  247.5    199.     314.     437.5    850.83   555.     699.95  1088.
  290.     375.     460.     188.5    680.     470.     597.75   570.
  272.5    329.95   480.     740.5    518.5    205.425  171.8    535.
  660.     391.5    395.     445.     770.    1450.     445.     260.
  822.5    430.     212.     660.5    784.     453.246  675.     199.
  220.     452.     382.5    519.95   665.     527.7    205.     420.
  500.     921.5    890.     430.     258.     511.     532.17   560.
  282.95  2250.     350.     215.     650.     320.     247.     320.
  255.     438.     900.     441.     420.     370.     269.95   807.1
  653.     371.5    284.     272.     313.     917.5    673.     425.
  399.95   385.     269.95   330.     260.     470.     589.     163.5
  835.    1095.     269.     560.     615.     585.188  305.     166.95
  799.     400.     230.     256.883  423.     465.     440.     385.
  210.     297.     470.     226.5    274.25   840.     677.9    425.
  180.25   464.     320.     625.504  592.5    465.     477.     280.
 1505.     445.838 1072.     467.     686.     279.95   527.     325.
  328.     390.     479.95   264.95   235.     516.5    655.     500.
  315.     213.     475.    1025.     416.     410.     800.     472.
  225.     210.     455.     225.     480.     363.    2400.     181.
  250.     481.     260.     455.     415.     349.5    245.     592.5
  385.     315.     255.     693.     780.     237.     525.     425.
  369.9    290.     285.     415.     272.5   2900.    1365.     436.
  210.     236.     331.     365.     450.     770.     455.     405.
  304.9    170.    2050.     780.     330.     370.     467.     405.
  675.     500.     389.999  630.     360.     580.     550.     879.
  265.     446.5    404.     267.5   3075.     335.     576.     208.633
  315.     725.     550.     610.75   550.7    665.     834.     201.
 2384.    1384.    1400.     305.     487.     390.     548.     268.75
  819.9    520.     230.     240.     232.     240.5    274.975  740.
  186.375  790.     880.     279.     295.     640.     940.     260.
  559.9    791.5    265.     245.     485.     684.     425.     309.6
  552.25   165.     239.9    320.     206.6    387.     299.     855.
  315.     437.5    252.     375.     300.     420.     900.     679.9
  463.     380.     329.5    604.95   795.     465.     673.     810.
  785.     338.     280.     315.     530.     380.     297.     730.
  450.     275.     595.     435.     270.     950.     389.     560.
 1350.     799.     365.5    252.35   403.95   385.     345.     490.
  330.     927.    1118.     330.     530.     365.     378.75   269.9
  557.     360.     352.     437.     322.5    650.     450.     278.5
  364.95   840.     268.     517.534  632.925  577.5    339.     570.
  563.5    423.     355.    1550.     482.     625.     538.     380.
  375.     245.     310.    1300.     397.     365.     328.5    988.
 1000.     237.     525.     749.     722.5    843.     438.     578.
  227.95   196.     641.     350.     205.     400.    1030.     505.
  475.     520.    1450.     333.5    232.     691.1    811.     551.
  496.5    705.     578.     255.    1050.     348.     230.     359.5
  330.      80.     465.     325.     340.5    342.5    290.9    868.7
 1199.    1150.     859.9    520.     460.     438.924  315.     590.
  378.5    328.5    849.95   525.    1385.     295.    1067.     207.95
  699.9   1280.     452.     370.     232.     669.95   397.5    490.
  725.     299.     625.     437.5    650.     475.     342.    1197.35
  280.     240.     529.     442.     615.    1485.     585.     480.
 1095.     290.     615.     300.     308.     750.    2250.     890.
  288.     190.     515.     235.     275.     727.5    650.    1600.
  365.     662.     270.5    200.     970.     160.     204.     358.
  452.     595.     249.     346.9   2125.     280.     318.888  530.
  375.     910.     782.     259.95   315.     215.     705.    1450.
  451.     261.     396.     725.    1950.     238.     750.     331.5
  460.     404.95   880.     863.     638.7    435.     260.     671.5
  610.     405.     338.9    720.     442.     650.     263.5    300.
  266.     930.     530.     180.     619.     264.     730.     439.
  268.5    330.     640.     900.     370.     685.     505.     265.
  290.     296.     360.     240.5    372.5    595.     515.    1220.
  507.     399.95   185.     460.     435.5    469.     531.     443.5
  223.     590.     340.     650.     533.6    695.     242.     425.
  525.     485.     175.     210.     260.     577.     200.     605.
  325.     289.5    559.95  1042.5    543.5    480.     218.     565.
  426.7    650.     542.     415.     214.     245.     314.5   1120.
  378.     305.     595.     729.5    430.     240.     545.     530.
  157.     425.     220.     521.     325.     597.5    337.    1000.
 3070.     495.     748.     888.     269.9    496.5    475.     312.
  323.     331.     306.     655.     290.    1250.     460.     435.
  664.     865.     385.     497.     280.     188.     478.5   1145.
  222.     799.     609.9    413.     400.     802.541  320.     507.
  387.5    396.     373.    1484.9    359.9    410.     690.     245.
  700.     268.     225.     980.     795.     195.     480.     485.
  130.     325.     440.     550.     310.     530.     390.     243.
  639.     215.     405.     250.     405.5    452.     730.     267.
  289.95   565.    1578.     636.     350.     320.     210.     245.
  328.     985.     501.     315.     403.     550.     347.5    365.
  588.     605.    1300.     233.     360.     459.     740.     305.
  395.     560.     650.     449.95   517.5    435.     329.999  950.
  447.     699.8    850.     316.5    942.5   1310.     856.6    405.6
  565.     400.     330.     374.95   405.3    560.     824.     260.
  760.     405.     429.9    341.5    465.25   450.     390.     420.
  269.95   493.     370.    2250.     305.     400.     320.     715.
  650.     218.     500.     460.     232.5    408.2    522.     675.
 1355.     249.95   210.     429.95   737.5    710.     470.    1100.
  650.    1216.     422.12   625.     385.2    500.     308.     565.
  581.     361.     345.     419.     347.     625.    2400.     379.
  310.     250.     682.     246.5    325.     310.95  1100.     287.5
  431.     226.     825.     175.     465.75   659.     595.     350.
  270.     662.5    249.9    324.5    430.     419.95   285.     332.
  282.     320.     428.75   330.     456.5    352.     664.     628.
  512.     254.     535.8    287.653  438.     450.     327.     370.5
  265.     450.     425.     166.6    245.     565.     539.9    910.
  280.     275.     467.     457.5    381.156  289.999  642.45   469.95
  795.     785.     860.    1095.     147.5    390.     229.     185.
  414.9    200.     225.     720.     930.    1270.     700.     466.
  374.     480.     740.    1010.     395.     340.     209.     431.65
  980.     660.     730.     291.5    905.     800.     839.9    200.
  300.     530.     314.95   255.     550.     435.     234.     615.
  205.     384.     324.     645.     570.     324.     270.     290.
  250.     342.     255.     800.     451.     990.     288.4    420.
  359.     390.     300.     545.     288.349  299.9    891.    1200.
  378.     299.995  253.     350.     565.     315.     570.     971.
  915.     419.     260.    1321.5    369.95  1029.9    435.     601.
  460.5    720.     851.     550.     700.     323.     345.5    378.
  650.     385.     425.     210.     630.     335.     196.5    582.8
  440.     752.5    532.5    265.     397.5    524.25   765.     648.
  469.5    237.5    216.     427.2    280.     718.     420.     379.
  326.1    535.     283.     260.     399.     484.95   640.     585.
  645.     253.     178.5    291.     199.95   553.5    189.95   289.   ]

1. Write code for gradient descent for training linear regression using the algorithm from class.

In [30]:
# gradient descent for training linear regression
# algorithm: thetaj <- thetaj - alpha*deritivative of J(theta)? - alpha is learning rate (small)
# algorithm should stop when: 1. update in theta is below some threshold or 2. maximum number of iterations reached (max_iterations var)
# choose initial value for theta - choose new values for theta to reduce J(theta) -> theta should get closer to minimum?

# gradient = slope of line tangent to curve

# features = x, price = y (both matrices?)
def gradient_descent(features, price, alpha, max_iterations):
    
    # initialize theta to 0?
    # length of theta vector should be amt of features + 1?
    theta = np.zeros(x_train.shape[1])
    N = x_train.shape[0]

    for iteration in range(0, max_iterations):
        # 1. get predicted values
        y_pred = features @ theta #?

        # 2. calc error difference btwn predicted and actual?
        error = y_pred - price

        # 3. gradient descent?
        gradient = (1/N) * (features.T @ error)

        # 4. update:
        theta = theta - alpha * gradient


        return theta

In [31]:
gradient_descent(matrix_train, price_matrix_train, 0.05, 100)

array([ 5.20953271,  8.26507882, 11.95717856,  2.48796658,  4.07071891,
        5.38062761,  7.55520933,  1.25480992, 10.9828817 ,  9.88108152,
        6.23268917,  0.27238569,  2.48293368,  6.20562492,  0.55725568,
       10.9448263 ,  2.74417647])