In [89]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [3]:
# import house_data dataset
original_dataset = pd.read_csv('kc_house_data.csv')
original_dataset.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [74]:
# import train dataset
train = pd.read_csv('train.csv')
train.head()

,Unnamed: 0,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,1,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,2,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,3,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,4,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,5,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [75]:
# import test dataset
test = pd.read_csv('test.csv')
test.head()

,Unnamed: 0,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,1001,3131200640,20150427T000000,700000.0,4,2.00,1830,4590,2.0,0,...,8,1830,0,1908,0,98105,47.6593,-122.327,1650,4590
1,1002,984000710,20141022T000000,270000.0,3,2.00,1560,8853,1.0,0,...,7,1560,0,1967,0,98058,47.4312,-122.171,1610,8750
2,1003,4167300350,20140508T000000,258000.0,4,1.75,1730,8320,1.0,0,...,7,1230,500,1977,0,98023,47.3270,-122.361,1840,9800
3,1004,2826049282,20140614T000000,530000.0,3,2.50,1930,7214,2.0,0,...,8,1930,0,2005,0,98125,47.7191,-122.309,1930,7266
4,1005,8946750030,20141218T000000,245000.0,3,2.25,1422,3677,2.0,0,...,7,1422,0,2012,0,98092,47.3204,-122.178,1677,3677

In [76]:
# TRAIN:
# ignore columns: id, date and zipcode
# also ignore price column because this is the response and what we are trying to predict
columns_to_drop = ['Unnamed: 0', 'zipcode', 'price']
x_train = train.drop(columns=columns_to_drop)
x_train.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15
0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,47.5112,-122.257,1340,5650
1,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,47.7210,-122.319,1690,7639
2,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,47.7379,-122.233,2720,8062
3,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,47.5208,-122.393,1360,5000
4,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,47.6168,-122.045,1800,7503

In [77]:
# TEST:
# ignore columns: id, date and zipcode
# also ignore price column because this is the response and what we are trying to predict
columns_to_drop = ['Unnamed: 0', 'id', 'date', 'zipcode', 'price']
x_test = test.drop(columns=columns_to_drop)
x_test.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15
0,4,2.00,1830,4590,2.0,0,0,3,8,1830,0,1908,0,47.6593,-122.327,1650,4590
1,3,2.00,1560,8853,1.0,0,0,3,7,1560,0,1967,0,47.4312,-122.171,1610,8750
2,4,1.75,1730,8320,1.0,0,0,3,7,1230,500,1977,0,47.3270,-122.361,1840,9800
3,3,2.50,1930,7214,2.0,0,0,3,8,1930,0,2005,0,47.7191,-122.309,1930,7266
4,3,2.25,1422,3677,2.0,0,0,3,7,1422,0,2012,0,47.3204,-122.178,1677,3677

In [94]:
# scale the data so that each feature has a mean of 0 and standard deviation of 1
scaler = StandardScaler()

# scale train dataset
for col in x_train:
    train_scaled = x_train[col].values.reshape(-1, 1) #reshape
    x_train[col] = scaler.fit_transform(train_scaled) 

# scale test dataset
for col in x_test:
    test_scaled = x_test[col].values.reshape(-1, 1) #reshape
    x_test[col] = scaler.fit_transform(test_scaled) 


# check mean and standard deviation of each feature to double check that scaling worked
for feature in x_train:
    mean = x_train.mean()
    std = x_train.var()

for feature in x_test:
    mean = x_test.mean()
    std = x_test.var()

# organize all variables into a table
stats_train = {
    'mean': mean,
    'std': std
}

stats_test = {
    'mean': mean,
    'std': std
}

feature_data_train = pd.DataFrame(stats_train)
feature_data_test = pd.DataFrame(stats_test)
feature_data_test

                       mean       std
bedrooms      -1.421085e-17  1.001001
bathrooms     -1.243450e-17  1.001001
sqft_living    1.243450e-17  1.001001
sqft_lot       1.065814e-17  1.001001
floors         5.151435e-17  1.001001
waterfront    -1.421085e-17  1.001001
view           4.440892e-18  1.001001
condition     -6.572520e-17  1.001001
grade         -2.131628e-17  1.001001
sqft_above     7.105427e-18  1.001001
sqft_basement -5.151435e-17  1.001001
yr_built      -3.552714e-18  1.001001
yr_renovated  -1.065814e-17  1.001001
lat            1.421085e-17  1.001001
long          -7.105427e-18  1.001001
sqft_living15 -1.065814e-17  1.001001
sqft_lot15     7.105427e-18  1.001001

In [95]:
# divide the price by 1000 for all rows in the train dataset
y_train = train['price'] / 1000
y_train

0      221.90
1      538.00
2      180.00
3      604.00
4      510.00
        ...
995    291.00
996    199.95
997    553.50
998    189.95
999    289.00
Name: price, Length: 1000, dtype: float64

In [96]:
# divide the price by 1000 for all rows in the test dataset
y_test = test['price'] / 1000
y_test

0      700.0
1      270.0
2      258.0
3      530.0
4      245.0
       ...
995    307.0
996    194.0
997    180.0
998    465.0
999    722.5
Name: price, Length: 1000, dtype: float64

In [105]:
# train multiple linear regression model on the training dataset
# using the existing python sklearn linear regression package:

model = LinearRegression()
model.fit(x_train, y_train)

# print model intercept
print("Intercept: ", model.intercept_)

# print model coefficient in a table with corresponding feature
coeff = {
    'feature': x_train.columns,
    'Coefficient': model.coef_ 
    }


pd.DataFrame(coeff)

Intercept:  520.4148339999999

          feature  Coefficient
0        bedrooms   -12.521962
1       bathrooms    18.527633
2     sqft_living    56.748837
3        sqft_lot    10.881868
4          floors     8.043721
5      waterfront    63.742900
6            view    48.200109
7       condition    12.964269
8           grade    92.231475
9      sqft_above    48.290089
10  sqft_basement    27.137032
11       yr_built   -67.643117
12   yr_renovated    17.271380
13            lat    78.375737
14           long    -1.035203
15  sqft_living15    45.577658
16     sqft_lot15   -12.930091

In [92]:
# find MSE and r^2 on training set

y_train_pred = model.predict(x_train)

MSE_train = mean_squared_error(y_train, y_train_pred)
r2_train = r2_score(y_train, y_train_pred)

print('MSE metric: ', MSE_train)
print('R squared metric: ', r2_train)

MSE metric:  31486.167775794882
R squared metric:  0.7265334318706018

In [93]:
# find MSE and r^2 on test set

y_test_pred = model.predict(x_test)

MSE_test = mean_squared_error(y_test, y_test_pred)
r2_test = r2_score(y_test, y_test_pred)

print('MSE metric: ', MSE_test)
print('R squared metric: ', r2_test)

MSE metric:  59784.365567516834
R squared metric:  0.6414235000248588