Use an existing package of your choice to train and test a logistic regression model on the SPAMBASE dataset.

In [4]:
import pandas as pd
from ucimlrepo import fetch_ucirepo 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score

In [5]:
# import fetch dataset 
spambase = fetch_ucirepo(id=94) 
  
# data (as pandas dataframes) 
X = spambase.data.features 
y = spambase.data.targets 
  
# metadata 
#print(spambase.metadata) 
  
# variable information 
#print(spambase.variables)

1. Split the original data into 75% for training and 25% for testing. Choose the training set at random. Train a logistic regression model on the training set and output the following **on the testing set**:
    1. **Confusion matrix**
    2. **Accuracy**, **Error**
    3. **Precision**, **Recall**, **F1 score**

In [6]:
# split data into training and test sets:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, shuffle=True) 

# train logistic regression model:
model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

/Users/pavithra/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/pavithra/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [7]:
# outputs:
print("Confusion matrix: ", confusion_matrix(y_test, y_pred))
print("Accuracy score: ", accuracy_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("Recall score: ", recall_score(y_test, y_pred))
print("F1 score: ", f1_score(y_test, y_pred))

Confusion matrix:  [[645  31]
 [ 53 422]]
Accuracy score:  0.9270199826238054
Precision:  0.9315673289183223
Recall score:  0.888421052631579
F1 score:  0.9094827586206896

2. Print the coefficients of the features in the model. Which features contribute mostly to the prediction? Which ones are positively
correlated and which ones are negatively correlated with the SPAM class?

In [8]:
# print model intercept
print("Intercept: ", model.intercept_)

# print model coefficient in a table with corresponding feature
coeff = {
    'Feature': X.columns,
    'Coefficient': model.coef_.flatten()
    }

pd.DataFrame(coeff)

Intercept:  [-1.28221939]

                       Feature  Coefficient
0               word_freq_make    -0.051284
1            word_freq_address    -0.131782
2                word_freq_all     0.174988
3                 word_freq_3d     0.256588
4                word_freq_our     0.928374
5               word_freq_over     0.440465
6             word_freq_remove     1.114780
7           word_freq_internet     0.731662
8              word_freq_order     0.250604
9               word_freq_mail     0.211884
10           word_freq_receive     0.089286
11              word_freq_will     0.030222
12            word_freq_people     0.097601
13            word_freq_report     0.028287
14         word_freq_addresses     0.260626
15              word_freq_free     1.154764
16          word_freq_business     0.722694
17             word_freq_email     0.342421
18               word_freq_you    -0.004231
19            word_freq_credit     0.461001
20              word_freq_your     0.257624
21              word_freq_font     0.185073
22               word_freq_000     0.979333
23             word_freq_money     0.490879
24                word_freq_hp    -2.481115
25               word_freq_hpl    -1.121066
26            word_freq_george    -3.368692
27               word_freq_650    -0.219487
28               word_freq_lab    -0.522706
29              word_freq_labs    -0.497238
30            word_freq_telnet    -0.314198
31               word_freq_857    -0.189251
32              word_freq_data    -0.674819
33               word_freq_415    -0.189737
34                word_freq_85    -0.538084
35        word_freq_technology    -0.131142
36              word_freq_1999    -0.580377
37             word_freq_parts    -0.142283
38                word_freq_pm    -0.457695
39            word_freq_direct    -0.173920
40                word_freq_cs    -0.336453
41           word_freq_meeting    -0.881484
42          word_freq_original    -0.256595
43           word_freq_project    -0.631536
44                word_freq_re    -0.957417
45               word_freq_edu    -1.217350
46             word_freq_table    -0.051625
47        word_freq_conference    -0.305090
48                 char_freq_;    -0.355614
49                 char_freq_(    -0.229832
50                 char_freq_[    -0.085996
51                 char_freq_!     0.397292
52                 char_freq_$     0.657698
53                 char_freq_#     0.192886
54  capital_run_length_average    -0.011961
55  capital_run_length_longest     0.007364
56    capital_run_length_total     0.000825

3. Vary the decision threshold $T \in \{0.25,0.5,0.75,0.9\}$ and report for each value the model accuracy, precision, and recall. Comment on
how these metrics vary with the choice of threshold.

In [13]:
thresholds = [0.25, 0.5, 0.75, 0.9]
rows = []
for T in thresholds:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=T, random_state=42, shuffle=True) 
    # scale the data: 
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled  = scaler.transform(X_test)
    
    # train logistic regression model:
    model = LogisticRegression()
    model.fit(X_train_scaled, y_train)

    y_pred = model.predict(X_test_scaled)

    # report scores
    rows.append({
        "Decision Threshold": T,
        "Confusion Matrix": confusion_matrix(y_test, y_pred),
        "Accuracy Score": accuracy_score(y_test, y_pred), 
        "Precision Score": precision_score(y_test, y_pred),
        "Recall Score": recall_score(y_test, y_pred),
        "F1 Score": f1_score(y_test, y_pred)
    })

pd.DataFrame(rows)

/Users/pavithra/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

/Users/pavithra/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/pavithra/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/pavithra/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

,Decision Threshold,Confusion Matrix,Accuracy Score,Precision Score,Recall Score,F1 Score
0,0.25,"[[649, 27], [62, 413]]",0.922676,0.938636,0.869474,0.902732
1,0.50,"[[1320, 69], [118, 794]]",0.918731,0.920046,0.870614,0.894648
2,0.75,"[[1930, 132], [192, 1197]]",0.906114,0.900677,0.861771,0.880795
3,0.90,"[[2312, 188], [229, 1412]]",0.899300,0.882500,0.860451,0.871336