Use an existing package of your choice to train and test a logistic regression model on the SPAMBASE dataset.

In [3]:
import pandas as pd
from ucimlrepo import fetch_ucirepo 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score

In [4]:
# import fetch dataset 
spambase = fetch_ucirepo(id=94) 
  
# data (as pandas dataframes) 
X = spambase.data.features 
y = spambase.data.targets 
  
# metadata 
print(spambase.metadata) 
  
# variable information 
print(spambase.variables)

{'uci_id': 94, 'name': 'Spambase', 'repository_url': 'https://archive.ics.uci.edu/dataset/94/spambase', 'data_url': 'https://archive.ics.uci.edu/static/public/94/data.csv', 'abstract': 'Classifying Email as Spam or Non-Spam', 'area': 'Computer Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 4601, 'num_features': 57, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': ['Class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1999, 'last_updated': 'Mon Aug 28 2023', 'dataset_doi': '10.24432/C53G6X', 'creators': ['Mark Hopkins', 'Erik Reeber', 'George Forman', 'Jaap Suermondt'], 'intro_paper': None, 'additional_info': {'summary': 'The "spam" concept is diverse: advertisements for products/web sites, make money fast schemes, chain letters, pornography...\n\nThe classification task for this dataset is to determine whether a given email is spam or not.\n\t\nOur collection of spam e-mails came from our postmaster and individuals who had filed spam.  Our collection of non-spam e-mails came from filed work and personal e-mails, and hence the word \'george\' and the area code \'650\' are indicators of non-spam.  These are useful when constructing a personalized spam filter.  One would either have to blind such non-spam indicators or get a very wide collection of non-spam to generate a general purpose spam filter.\n\nFor background on spam: Cranor, Lorrie F., LaMacchia, Brian A.  Spam!, Communications of the ACM, 41(8):74-83, 1998.\n\nTypical performance is around ~7% misclassification error. False positives (marking good mail as spam) are very undesirable.If we insist on zero false positives in the training/testing set, 20-25% of the spam passed through the filter. See also Hewlett-Packard Internal-only Technical Report. External version forthcoming. ', 'purpose': None, 'funded_by': None, 'instances_represent': 'Emails', 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'The last column of \'spambase.data\' denotes whether the e-mail was considered spam (1) or not (0), i.e. unsolicited commercial e-mail.  Most of the attributes indicate whether a particular word or character was frequently occuring in the e-mail.  The run-length attributes (55-57) measure the length of sequences of consecutive capital letters.  For the statistical measures of each attribute, see the end of this file.  Here are the definitions of the attributes:\r\n\r\n48 continuous real [0,100] attributes of type word_freq_WORD \r\n= percentage of words in the e-mail that match WORD, i.e. 100 * (number of times the WORD appears in the e-mail) / total number of words in e-mail.  A "word" in this case is any string of alphanumeric characters bounded by non-alphanumeric characters or end-of-string.\r\n\r\n6 continuous real [0,100] attributes of type char_freq_CHAR] \r\n= percentage of characters in the e-mail that match CHAR, i.e. 100 * (number of CHAR occurences) / total characters in e-mail\r\n\r\n1 continuous real [1,...] attribute of type capital_run_length_average \r\n= average length of uninterrupted sequences of capital letters\r\n\r\n1 continuous integer [1,...] attribute of type capital_run_length_longest \r\n= length of longest uninterrupted sequence of capital letters\r\n\r\n1 continuous integer [1,...] attribute of type capital_run_length_total \r\n= sum of length of uninterrupted sequences of capital letters \r\n= total number of capital letters in the e-mail\r\n\r\n1 nominal {0,1} class attribute of type spam\r\n= denotes whether the e-mail was considered spam (1) or not (0), i.e. unsolicited commercial e-mail.  \r\n', 'citation': None}}
                          name     role        type demographic  \
0               word_freq_make  Feature  Continuous        None
1            word_freq_address  Feature  Continuous        None
2                word_freq_all  Feature  Continuous        None
3                 word_freq_3d  Feature  Continuous        None
4                word_freq_our  Feature  Continuous        None
5               word_freq_over  Feature  Continuous        None
6             word_freq_remove  Feature  Continuous        None
7           word_freq_internet  Feature  Continuous        None
8              word_freq_order  Feature  Continuous        None
9               word_freq_mail  Feature  Continuous        None
10           word_freq_receive  Feature  Continuous        None
11              word_freq_will  Feature  Continuous        None
12            word_freq_people  Feature  Continuous        None
13            word_freq_report  Feature  Continuous        None
14         word_freq_addresses  Feature  Continuous        None
15              word_freq_free  Feature  Continuous        None
16          word_freq_business  Feature  Continuous        None
17             word_freq_email  Feature  Continuous        None
18               word_freq_you  Feature  Continuous        None
19            word_freq_credit  Feature  Continuous        None
20              word_freq_your  Feature  Continuous        None
21              word_freq_font  Feature  Continuous        None
22               word_freq_000  Feature  Continuous        None
23             word_freq_money  Feature  Continuous        None
24                word_freq_hp  Feature  Continuous        None
25               word_freq_hpl  Feature  Continuous        None
26            word_freq_george  Feature  Continuous        None
27               word_freq_650  Feature  Continuous        None
28               word_freq_lab  Feature  Continuous        None
29              word_freq_labs  Feature  Continuous        None
30            word_freq_telnet  Feature  Continuous        None
31               word_freq_857  Feature  Continuous        None
32              word_freq_data  Feature  Continuous        None
33               word_freq_415  Feature  Continuous        None
34                word_freq_85  Feature  Continuous        None
35        word_freq_technology  Feature  Continuous        None
36              word_freq_1999  Feature  Continuous        None
37             word_freq_parts  Feature  Continuous        None
38                word_freq_pm  Feature  Continuous        None
39            word_freq_direct  Feature  Continuous        None
40                word_freq_cs  Feature  Continuous        None
41           word_freq_meeting  Feature  Continuous        None
42          word_freq_original  Feature  Continuous        None
43           word_freq_project  Feature  Continuous        None
44                word_freq_re  Feature  Continuous        None
45               word_freq_edu  Feature  Continuous        None
46             word_freq_table  Feature  Continuous        None
47        word_freq_conference  Feature  Continuous        None
48                 char_freq_;  Feature  Continuous        None
49                 char_freq_(  Feature  Continuous        None
50                 char_freq_[  Feature  Continuous        None
51                 char_freq_!  Feature  Continuous        None
52                 char_freq_$  Feature  Continuous        None
53                 char_freq_#  Feature  Continuous        None
54  capital_run_length_average  Feature  Continuous        None
55  capital_run_length_longest  Feature  Continuous        None
56    capital_run_length_total  Feature  Continuous        None
57                       Class   Target      Binary        None

                 description units missing_values
0                       None  None             no
1                       None  None             no
2                       None  None             no
3                       None  None             no
4                       None  None             no
5                       None  None             no
6                       None  None             no
7                       None  None             no
8                       None  None             no
9                       None  None             no
10                      None  None             no
11                      None  None             no
12                      None  None             no
13                      None  None             no
14                      None  None             no
15                      None  None             no
16                      None  None             no
17                      None  None             no
18                      None  None             no
19                      None  None             no
20                      None  None             no
21                      None  None             no
22                      None  None             no
23                      None  None             no
24                      None  None             no
25                      None  None             no
26                      None  None             no
27                      None  None             no
28                      None  None             no
29                      None  None             no
30                      None  None             no
31                      None  None             no
32                      None  None             no
33                      None  None             no
34                      None  None             no
35                      None  None             no
36                      None  None             no
37                      None  None             no
38                      None  None             no
39                      None  None             no
40                      None  None             no
41                      None  None             no
42                      None  None             no
43                      None  None             no
44                      None  None             no
45                      None  None             no
46                      None  None             no
47                      None  None             no
48                      None  None             no
49                      None  None             no
50                      None  None             no
51                      None  None             no
52                      None  None             no
53                      None  None             no
54                      None  None             no
55                      None  None             no
56                      None  None             no
57  spam (1) or not spam (0)  None             no

1. Split the original data into 75% for training and 25% for testing. Choose the training set at random. Train a logistic regression model on the training set and output the following **on the testing set**:
    1. **Confusion matrix**
    2. **Accuracy**, **Error**
    3. **Precision**, **Recall**, **F1 score**

In [5]:
# split data into training and test sets:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, shuffle=True) 

# train logistic regression model:
model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

/Users/pavithra/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/pavithra/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [6]:
# outputs:
print("Confusion matrix: ", confusion_matrix(y_test, y_pred))
print("Accuracy error: ", accuracy_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred))
print("Recall score: ", recall_score(y_test, y_pred))
print("F1 score: ", f1_score(y_test, y_pred))

Confusion matrix:  [[645  31]
 [ 53 422]]
Accuracy error:  0.9270199826238054
Precision:  0.9315673289183223
Recall score:  0.888421052631579
F1 score:  0.9094827586206896

2. Print the coefficients of the features in the model. Which features contribute mostly to the prediction? Which ones are positively
correlated and which ones are negatively correlated with the SPAM class?

In [7]:
# print model intercept
print("Intercept: ", model.intercept_)

# print model coefficient in a table with corresponding feature
coeff = {
    'Feature': X.columns,
    'Coefficient': model.coef_.flatten()
    }


pd.DataFrame(coeff)

Intercept:  [-1.28221939]

                       Feature  Coefficient
0               word_freq_make    -0.051284
1            word_freq_address    -0.131782
2                word_freq_all     0.174988
3                 word_freq_3d     0.256588
4                word_freq_our     0.928374
5               word_freq_over     0.440465
6             word_freq_remove     1.114780
7           word_freq_internet     0.731662
8              word_freq_order     0.250604
9               word_freq_mail     0.211884
10           word_freq_receive     0.089286
11              word_freq_will     0.030222
12            word_freq_people     0.097601
13            word_freq_report     0.028287
14         word_freq_addresses     0.260626
15              word_freq_free     1.154764
16          word_freq_business     0.722694
17             word_freq_email     0.342421
18               word_freq_you    -0.004231
19            word_freq_credit     0.461001
20              word_freq_your     0.257624
21              word_freq_font     0.185073
22               word_freq_000     0.979333
23             word_freq_money     0.490879
24                word_freq_hp    -2.481115
25               word_freq_hpl    -1.121066
26            word_freq_george    -3.368692
27               word_freq_650    -0.219487
28               word_freq_lab    -0.522706
29              word_freq_labs    -0.497238
30            word_freq_telnet    -0.314198
31               word_freq_857    -0.189251
32              word_freq_data    -0.674819
33               word_freq_415    -0.189737
34                word_freq_85    -0.538084
35        word_freq_technology    -0.131142
36              word_freq_1999    -0.580377
37             word_freq_parts    -0.142283
38                word_freq_pm    -0.457695
39            word_freq_direct    -0.173920
40                word_freq_cs    -0.336453
41           word_freq_meeting    -0.881484
42          word_freq_original    -0.256595
43           word_freq_project    -0.631536
44                word_freq_re    -0.957417
45               word_freq_edu    -1.217350
46             word_freq_table    -0.051625
47        word_freq_conference    -0.305090
48                 char_freq_;    -0.355614
49                 char_freq_(    -0.229832
50                 char_freq_[    -0.085996
51                 char_freq_!     0.397292
52                 char_freq_$     0.657698
53                 char_freq_#     0.192886
54  capital_run_length_average    -0.011961
55  capital_run_length_longest     0.007364
56    capital_run_length_total     0.000825

3. Vary the decision threshold $T \in \{0.25,0.5,0.75,0.9\}$ and report for each value the model accuracy, precision, and recall. Comment on
how these metrics vary with the choice of threshold.

In [11]:
thresholds = [0.25, 0.5, 0.75, 0.9]
rows = []
for T in thresholds:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=T, random_state=42, shuffle=True) 
    
    # train logistic regression model:
    model = LogisticRegression()
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    # report scores
    rows.append({
        "Decision Threshold": T,
        "Confusion Matrix": confusion_matrix(y_test, y_pred),
        "Accuracy Score": accuracy_score(y_test, y_pred), 
        "Precision Score": precision_score(y_test, y_pred),
        "Recall Score": recall_score(y_test, y_pred),
        "F1 Score": f1_score(y_test, y_pred)
    })

pd.DataFrame(rows)

/Users/pavithra/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/pavithra/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/pavithra/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/pavithra/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/pavithra/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/pavithra/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/pavithra/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/pavithra/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

,Decision Threshold,Confusion Matrix,Accuracy Score,Precision Score,Recall Score,F1 Score
0,0.25,"[[645, 31], [53, 422]]",0.927020,0.931567,0.888421,0.909483
1,0.50,"[[1301, 88], [107, 805]]",0.915254,0.901456,0.882675,0.891967
2,0.75,"[[1877, 185], [137, 1252]]",0.906694,0.871260,0.901368,0.886058
3,0.90,"[[2306, 194], [165, 1476]]",0.913306,0.883832,0.899452,0.891574